# Generated by Django 5.0.2 on 2024-02-29 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitise', '0002_alter_user_negative_habits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='negative_habits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='positive_habits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), size=None),
        ),
    ]
