# Generated by Django 5.0.2 on 2024-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitise', '0004_alter_user_negative_habits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
