# Generated by Django 5.0.2 on 2024-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitise', '0005_alter_habitmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='emoji_unicode_hex',
            field=models.CharField(default='U+1FAA5', max_length=7),
            preserve_default=False,
        ),
    ]
