# Generated by Django 5.0.2 on 2024-03-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitise', '0007_alter_user_negative_habits_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackedHabit',
            new_name='TrackedHabitsModel',
        ),
    ]
